### PR TITLE
My first pull request, is this the way documentation should be done? Waiting for feedback.

### PR DESCRIPTION
**Pull request by Ameen-Here**
## Description

- [x] I have followed the [code of conduct](https://github.com/Alphasians/AINA/blob/main/contributing.md)
- [x] I have followed the [contributing guidelines](https://github.com/Alphasians/AINA/blob/main/contributing.md).
- [x] Either I have tested the code or my changes are not related to code.

## Related Issue

fixes # 
Documentation work. 
Tried documenting only one functionality as a demo, this is for knowing the feedback

### CODE REVIEW

**Comment by Sonichigo** [comment]
@Ameen-Here LGTM 👌

**Comment by Ameen-Here** [comment]
> @Ameen-Here LGTM 👌
> Yeah, this way documentation are made!!

So can I continue the same way. And thanks for the feedback!!!

**Comment by Sonichigo** [comment]
> > @Ameen-Here LGTM 👌
> > Yeah, this way documentation are made!!
> 
> So can I continue the same way. And thanks for the feedback!!!

Yes. Continue in the same way!! And if you have any doubt u can ask in our discord server https://discord.gg/bTUVVq83BB

**Review by krishdevdb — CHANGES_REQUESTED** [review]
Maybe switch the file extension (.md.txt) to just .md

**Comment by Sonichigo** [comment]
> Maybe switch the file extension (.md.txt) to just .md

Thanks for pointing it out, i missed that😅. Make the necessary changes @Ameen-Here

**Comment by Ameen-Here** [comment]
> Maybe switch the file extension (.md.txt) to just .md

Sure, I will. Thanks for the feedback

**Comment by Ameen-Here** [comment]
Have added all the required documentation, can you please help me out what's the next step if any?

**Review by krishdevdb — APPROVED** [review]
LGTM 🚀 RR: @Sonichigo

**Comment by Ameen-Here** [comment]
Should I need to do anything specific, I really don't know what happens next? Sorry for los of naive questions, this is my first open source contribution, that's why.

**Comment by Sonichigo** [comment]
> Should I need to do anything specific, I really don't know what happens next? Sorry for los of naive questions, this is my first open source contribution, that's why.

LGTM 🍀

**Pull request merged**
